### ISSUE TITLE
Issues with question 9

### ISSUE THREAD

**Issue by Nerajno** [learn-co-curriculum/pfwtfp-enumerable-drills-lab#3]
_**This solution code doesn't work**_  
def using_any?(arr)
 arr.any? { |item| item.to_a?(Integer)}
 end

**_However this wrks_**
def using_any?(array)
  array.any? { |int| int.is_a?(Integer)}
end

**Comment by sgharms** [comment]
As of 68ea95d84d07 in the solution branch, I was able to run this fine. Maybe you got an older version? In any case, this should be OK now.
